image: docker:24.0

services:
  - name: docker:24.0-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_BUILDKIT: "1"

stages: [build]

build_and_test:
  stage: build
  before_script:
    - docker info
  script:
    - docker build --progress=plain --target test .
    - docker build --progress=plain --tag local/app:${CI_COMMIT_SHA} .
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
