name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build test target
        uses: docker/build-push-action@v6
        with:
          context: .
          target: test
          push: false

      - name: Build final image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: local/app:${{ github.sha }}
