name: ci

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build test target (pytest runs inside image)
        uses: docker/build-push-action@v6
        with:
          context: .
          target: test
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build final image
        if: ${{ success() }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: local/app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
